### ISSUE TITLE
Is this package the right location for the xxhash non-cryyptographic hash function 

### ISSUE THREAD

**Issue by tonyalaribe** [vincenthz/cryptonite#368]
I have a need for xxhash3 and couldn't find a haskell package that offers it. Is this the right location for such an algorithm? And is it ok if I create a PR for it here ?

For reference, it's one of the fastest hash functions out there:
https://github.com/Cyan4973/xxHash

**Comment by NicolasDP** [comment]
I think it would be better in `Foundation` here: https://github.com/haskell-foundation/foundation/tree/master/foundation/Foundation/Hashing

**Comment by tonyalaribe** [comment]
But then it won't be accessible to people who don't use foundation as their prelude, no?
